repos:
  - repo: local
  
    hooks:
    
    - id: ruff_fix
      name: ruff_fix
      entry: uv
      args: ["run", "ruff","check", ".", "--fix"]
      language: system
      types: [python]

    - id: ruff_format
      name: ruff_format
      entry: run
      args: ["run", "ruff", "format", "."]
      language: system
      types: [python]
