repos:
  - repo: local
  
    hooks:
    
    - id: ruff_fix
      name: ruff_fix
      entry: ruff
      args: ["check", ".", "--fix"]
      language: system
      types: [python]

    - id: ruff_format
      name: ruff_format
      entry: ruff
      args: ["format", "."]
      language: system
      types: [python]
